name: internationalization
description: A projeto to easily implemente internationalization on flutter projects
version: 1.0.0
author: Tércyo Storck <tercyostorck@gmail.com>
homepage: https://github.com/TercyoStorck
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: